services:
    
  bot:
      build:
        context: ./bot
        dockerfile: Dockerfile
      volumes:
        - ./:/home/jovyan/

  flask:
      build:
        context: ./flask
        dockerfile: Dockerfile
      volumes:
        - ./:/home/jovyan/

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      